{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter  #  tkinterをインポート"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()  # Tk()クラスはTkのインスタンスを返し、rootに代入。rootがメインウィンドウに対応する\n",
    "root.title(\"Python Tkinter\")  #  メインウィンドウのタイトル\n",
    "root.geometry(\"300x250\")  #  ウィンドウサイズ\n",
    "root.mainloop()  #  イベントループ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"Python Tkinter\")\n",
    "root.geometry(\"300x250\")\n",
    "btn = tkinter.Button(root, text=\"OK\")  # ボタンウィジェットのインスタンス生成\n",
    "btn.pack()  # ウィンドウに配置\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"Label\")\n",
    "root.geometry(\"300x250\")\n",
    "lb = tkinter.Label(root, text=\"hello python\")\n",
    "lb.pack()\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"Label\")\n",
    "root.geometry(\"300x250\")\n",
    "lb = tkinter.Label(text=\"Python\", foreground=\"white\", background=\"blue\")\n",
    "lb.pack()\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"Label\")\n",
    "root.geometry(\"300x250\")\n",
    "lb = tkinter.Label(text=\"Python\", font=(u\"MS明朝\",30,\"bold\"))\n",
    "lb.pack()\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.option_add(\"*font\", \"Monospace 30\")\n",
    "tk.Label(text=\"Hello\").pack()\n",
    "tk.Label(text=\"Python\").pack()\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "lb = tkinter.Label(text=\"Python\")\n",
    "lb.pack()\n",
    "\n",
    "lb.configure(bg=\"yellow\")\n",
    "lb.configure(fg=\"green\")\n",
    "lb.cget(\"text\")\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "lb_str = tkinter.StringVar()\n",
    "lb_str.set(\"Hello\")\n",
    "lb = tkinter.Label(textvariable=lb_str, bg=\"yellow\")\n",
    "lb.pack()\n",
    "lb_str.set(\"Python\")\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.title(\"pack\")\n",
    "color = (\"red\",\"blue\",\"yellow\",\"green\")\n",
    "\n",
    "for x in range(4):\n",
    "    label = tkinter.Label(root, text=f\"Label{x}\", background=color[x])\n",
    "#     label.pack()\n",
    "#     label.pack(fill=\"both\")\n",
    "    label.pack(side=\"left\")\n",
    "    \n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.title(\"packer\")\n",
    "color = (\"red\", \"yellow\", \"green\", \"blue\")\n",
    "\n",
    "label1 = tkinter.Label(root, text=\"label1\", background=color[0])\n",
    "label2 = tkinter.Label(root, text=\"label2\", background=color[1])\n",
    "label3 = tkinter.Label(root, text=\"label3\", background=color[2])\n",
    "label4 = tkinter.Label(root, text=\"label4\", background=color[3])\n",
    "\n",
    "label1.grid(column=0, row=0)\n",
    "label2.grid(column=1, row=0)\n",
    "label3.grid(column=0, row=1)\n",
    "label4.grid(column=1, row=1)\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.title(\"placer\")\n",
    "color = (\"red\", \"yellow\", \"green\", \"blue\")\n",
    "\n",
    "for x in range(4):\n",
    "    lb = tkinter.Label(root, text=f\"Label{x}\", bg=color[x])\n",
    "#     lb.place(relx=0.25*x, rely=0.25*x)\n",
    "    lb.place(x=50*x, y=40*x)\n",
    "    \n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.title(\"Button\")\n",
    "\n",
    "btn = tkinter.Button(text=\"Button1\", width=10)\n",
    "btn.pack()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.title(\"Button\")\n",
    "\n",
    "def button_on():\n",
    "    lb_str.set(\"ON\")\n",
    "    \n",
    "def button_off():\n",
    "    lb_str.set(\"OFF\")\n",
    "\n",
    "lb_str = tkinter.StringVar()\n",
    "lb_str.set(\"NON\")\n",
    "\n",
    "tkinter.Label(textvariable=lb_str).pack()\n",
    "\n",
    "btn_on = tkinter.Button(text=\"ON\", width=3, command=button_on)\n",
    "btn_on.pack()\n",
    "\n",
    "btn_off = tkinter.Button(text=\"OFF\", width=3, command=button_off)\n",
    "btn_off.pack()\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: button_off() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: button_on() takes 0 positional arguments but 1 was given\n"
     ]
    }
   ],
   "source": [
    "root = tkinter.Tk()\n",
    "root.geometry(\"300x250\")\n",
    "root.title(\"Button\")\n",
    "\n",
    "def button_on():\n",
    "    lb_str.set(\"ON\")\n",
    "    \n",
    "def button_off():\n",
    "    lb_str.set(\"OFF\")\n",
    "\n",
    "lb_str = tkinter.StringVar()\n",
    "lb_str.set(\"NON\")\n",
    "\n",
    "tkinter.Label(textvariable=lb_str).pack()\n",
    "\n",
    "btn_on = tkinter.Button(text=\"ON\", width=3)\n",
    "btn_on.bind(\"<Button-1>\", button_on)\n",
    "btn_on.pack()\n",
    "\n",
    "btn_off = tkinter.Button(text=\"OFF\", width=3)\n",
    "btn_off.bind(\"<Button-1>\", button_off)\n",
    "btn_off.pack()\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"Entry\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "# entry = tkinter.Entry()\n",
    "entry = tkinter.Entry(width=20)\n",
    "entry.insert(tkinter.END, \"名前の入力\")\n",
    "entry.pack()\n",
    "\n",
    "# input_ = entry.get()\n",
    "entry.delete(0, tkinter.END)\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"frame\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "frame1 = tkinter.Frame(root)\n",
    "frame2 = tkinter.Frame(root)\n",
    "\n",
    "tkinter.Label(frame1, text=\"ボタンを押してください\").pack()\n",
    "tkinter.Button(frame1, text=\"Button1\").pack(side=\"left\")\n",
    "tkinter.Button(frame1, text=\"Button2\").pack(side=\"left\")\n",
    "tkinter.Button(frame1, text=\"Button3\").pack(side=\"left\")\n",
    "\n",
    "tkinter.Button(text=\"Button4\").pack(in_ = frame2, fill=\"both\")\n",
    "tkinter.Button(text=\"Button5\").pack(in_ = frame2, fill=\"both\")\n",
    "tkinter.Button(text=\"Button6\").pack(in_ = frame2, fill=\"both\")\n",
    "\n",
    "frame1.pack()\n",
    "frame2.pack(fill=\"both\")\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"scale\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "s1 = tkinter.Scale(root, from_=0, to=255, orient=\"h\", length=200)\n",
    "s1.pack()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "TypeError: change_color() takes 0 positional arguments but 1 was given\n"
     ]
    }
   ],
   "source": [
    "root = tkinter.Tk()\n",
    "root.title(\"Scale\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "def change_color():\n",
    "    color = \"#{:02x}{:02x}{:02x}\".format(int(n), 0, 0)\n",
    "    color_label.configure(bg=color)\n",
    "    \n",
    "color_label = tkinter.Label(root, text=\"COLOR\", bg=\"#000\", fg=\"white\")\n",
    "color_label.pack(fill=\"both\")\n",
    "\n",
    "s1 = tkinter.Scale(root, label=\"red\", from_=0, to=255, orient=\"h\", command=change_color)\n",
    "s1.pack(fill=\"both\")\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    " \n",
    "# Main Window \n",
    "root = tk.Tk()\n",
    "root.title(\"Tkinter:Scale\")\n",
    "root.geometry(\"300x200\")\n",
    " \n",
    "# Change background color \n",
    "def change_color( n ):\n",
    "    color = '#{:02x}{:02x}{:02x}'.format(int(n), 0, 0)\n",
    "    color_label.configure(bg = color)\n",
    " \n",
    "# color_Label \n",
    "color_label = tk.Label(root, text = 'COLOR', bg = '#000', fg='white')\n",
    "color_label.pack(fill = 'both');\n",
    " \n",
    "# Scale \n",
    "s1 = tk.Scale(root, label = 'red', orient = 'h',\n",
    "           from_ = 0, to = 255, command = change_color)\n",
    " \n",
    "# Layout and styling widged\n",
    "s1.pack(fill = 'both')\n",
    " \n",
    "# Main\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"400\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"800\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"1300\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"3300\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"4400\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"5200\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"6000\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"6600\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"7000\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"7400\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"7800\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"8100\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"8200\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"8400\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"8500\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"8503\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85020\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85026\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85035\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85045\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85055\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85061\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85073\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85081\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85083\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85085\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-91-4e1d3a0a9ffc>\", line 19, in change_color\n",
      "    color_label.configure(bg=color)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1485, in configure\n",
      "    return self._configure('configure', cnf, kw)\n",
      "  File \"/Users/ishidzukahiroyuki/.pyenv/versions/anaconda3-2019.07/lib/python3.7/tkinter/__init__.py\", line 1476, in _configure\n",
      "    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))\n",
      "_tkinter.TclError: unknown color name \"85086\"\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    " \n",
    "# Main Window \n",
    "root = tk.Tk()\n",
    "root.title(\"Tkinter:Scale\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "red = tk.IntVar()\n",
    "red.set(0)\n",
    "blue = tk.IntVar()\n",
    "blue.set(0)\n",
    "green = tk.IntVar()\n",
    "green.set(0)\n",
    " \n",
    "# Change background color \n",
    "def change_color( n ):\n",
    "#     color = '#{:02x}{:02x}{:02x}'.format(int(n), 0, 0)\n",
    "    color = f\"{red.get()}{green.get()}{blue.get()}\"\n",
    "    color_label.configure(bg=color)\n",
    "\n",
    "# color_Label \n",
    "color_label = tk.Label(root, text = 'COLOR', bg = '#000')\n",
    "color_label.pack(fill = 'both');\n",
    " \n",
    "# Scale \n",
    "s1 = tk.Scale(root, label = 'red', orient = 'h',\n",
    "           from_ = 0, to = 255, variable=red, command = change_color)\n",
    "s2 = tk.Scale(root, label = 'blue', orient = 'h',\n",
    "           from_ = 0, to = 255, variable=blue, command = change_color)\n",
    "s3 = tk.Scale(root, label = 'blue', orient = 'h',\n",
    "           from_ = 0, to = 255, variable=blue, command = change_color)\n",
    " \n",
    "# Layout and styling widged\n",
    "s1.pack(fill = 'both')\n",
    "s2.pack(fill = 'both')\n",
    "s3.pack(fill = 'both')\n",
    " \n",
    "# Main\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    " \n",
    "# Main Window \n",
    "root = tk.Tk()\n",
    "root.title(\"Tkinter:Scale\")\n",
    "root.geometry(\"300x200\")\n",
    " \n",
    "# Define the scales\n",
    "red = tk.IntVar()\n",
    "red.set(0)\n",
    "blue = tk.IntVar()\n",
    "blue.set(0)\n",
    "green = tk.IntVar()\n",
    "green.set(0)\n",
    " \n",
    "# Change background color \n",
    "def change_color( n ):\n",
    "#   color = '#%02x%02x%02x' % (red.get(), green.get(), blue.get())\n",
    "    color = '#{:02x}{:02x}{:02x}'.format(red.get(), green.get(), blue.get())\n",
    "    color_label.configure(bg = color)\n",
    "\n",
    "# color_Label \n",
    "color_label = tk.Label(root, text = 'COLOR', bg = '#000')\n",
    "color_label.pack(fill = 'both');\n",
    " \n",
    "# Scale \n",
    "s1 = tk.Scale(root, label = 'red', orient = 'h',\n",
    "           from_ = 0, to = 255, variable = red,\n",
    "           command = change_color)\n",
    " \n",
    "s2 = tk.Scale(root, label = 'blue', orient = 'h',\n",
    "           from_ = 0, to = 255, variable = blue,\n",
    "           command = change_color)\n",
    " \n",
    "s3 = tk.Scale(root, label = 'green', orient = 'h',\n",
    "           from_ = 0, to = 255, variable = green,\n",
    "           command = change_color)\n",
    " \n",
    "# Layout and styling widged\n",
    "s1.pack(fill = 'both')\n",
    "s2.pack(fill = 'both')\n",
    "s3.pack(fill = 'both')\n",
    " \n",
    "# Main\n",
    "root.mainloop()\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "variable:  True\n",
      "variable:  False\n",
      "variable:  True\n",
      "variable:  False\n",
      "variable:  True\n",
      "variable:  False\n"
     ]
    }
   ],
   "source": [
    "root = tk.Tk()\n",
    "root.title(\"checkbtn\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "cnk = tk.BooleanVar()\n",
    "cnk.set(False)\n",
    "\n",
    "def checked():\n",
    "    print(\"variable: \", cnk.get())\n",
    "    \n",
    "check_btn = tk.Checkbutton(variable=cnk, text=\"Check\", command=checked)\n",
    "check_btn.pack()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tk.Tk()\n",
    "root.title(\"checkbtn\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "on_off = {True: \"ON\", False: \"OFF\"}\n",
    "\n",
    "lb = tk.Label(root, text=on_off[False])\n",
    "lb.pack()\n",
    "\n",
    "cnk = tk.BooleanVar()\n",
    "cnk.set(False)\n",
    "\n",
    "def checked():\n",
    "#     print(\"variable: \", cnk.get())\n",
    "    lb.configure(text=on_off[cnk.get()])\n",
    "    \n",
    "check_btn = tk.Checkbutton(variable=cnk, text=\"Check\", command=checked)\n",
    "check_btn.pack()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "\n",
    "root = tk.Tk()\n",
    "root.title(\"RadioBTN\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "def change_state():\n",
    "    btn = v.get()\n",
    "    if btn == 1:\n",
    "        radio2.configure(state=\"disable\")\n",
    "        radio3.configure(state=\"disable\")\n",
    "    elif btn == 2:\n",
    "        radio1.configure(state=\"disable\")\n",
    "        radio3.configure(state=\"disable\")\n",
    "    elif btn == 3:\n",
    "        radio1.configure(state=\"disable\")\n",
    "        radio2.configure(state=\"disable\")\n",
    "    elif btn == 0:\n",
    "        pass\n",
    "    else:\n",
    "        print(\"Error\", btn)\n",
    "\n",
    "v = tk.IntVar()\n",
    "v.set(0)\n",
    "\n",
    "radio1 = tk.Radiobutton(text=\"選択項目１\", variable=v, value=1, command=change_state)\n",
    "radio1.pack()\n",
    "radio2 = tk.Radiobutton(text=\"選択項目2\", variable=v, value=2, command=change_state)\n",
    "radio2.pack()\n",
    "radio3 = tk.Radiobutton(text=\"選択項目3\", variable=v, value=3, command=change_state)\n",
    "radio3.pack()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    " \n",
    "root = tk.Tk()\n",
    "root.title(\"Raidobutton機能\")\n",
    "root.geometry(\"200x150\")\n",
    " \n",
    "# 選択されたラジオボタン以外を無効にする\n",
    "def change_state():\n",
    "    btn = v.get()\n",
    " \n",
    "    if btn == 1:\n",
    "        radio2.configure(state = \"disabled\")\n",
    "        radio3.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 2:\n",
    "        radio1.configure(state = \"disabled\")\n",
    "        radio3.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 3:\n",
    "        radio1.configure(state = \"disabled\")\n",
    "        radio2.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 0:\n",
    "        pass\n",
    " \n",
    "    else:\n",
    "        print(\"Error\",btn)\n",
    "\n",
    "v = tk.IntVar()\n",
    "v.set(0)\n",
    " \n",
    "# ラジオボタン・オブジェクトの生成と配置\n",
    "radio1 = tk.Radiobutton(text=\"選択項目#1\", variable = v, value = 1, command = change_state)\n",
    "radio1.pack()\n",
    " \n",
    "radio2 = tk.Radiobutton(text=\"選択項目#2\", variable = v, value = 2, command = change_state)\n",
    "radio2.pack()\n",
    " \n",
    "radio3 = tk.Radiobutton(text=\"選択項目#3\", variable = v, value = 3, command = change_state)\n",
    "radio3.pack()\n",
    " \n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    " \n",
    "root = tk.Tk()\n",
    "root.title(\"Raidobutton機能\")\n",
    "root.geometry(\"200x150\")\n",
    " \n",
    "# 選択されたラジオボタン以外を無効にする\n",
    "def state1():\n",
    "    btn = v1.get()\n",
    " \n",
    "    if btn == 1:\n",
    "        radio12.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 2:\n",
    "        radio11.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 0:\n",
    "        pass\n",
    " \n",
    "    else:\n",
    "        print(\"Error\",btn)\n",
    "\n",
    "def state2():\n",
    "    btn = v2.get()\n",
    "    if btn == 1:\n",
    "        radio22.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 2:\n",
    "        radio21.configure(state = \"disabled\")\n",
    " \n",
    "    elif btn == 0:\n",
    "        pass\n",
    " \n",
    "    else:\n",
    "        print(\"Error\",btn)\n",
    "\n",
    "# 選択ボタンのリセット\n",
    "def reset():\n",
    "    radio11.configure(state = \"normal\")\n",
    "    radio12.configure(state = \"normal\")\n",
    "    radio21.configure(state = \"normal\")\n",
    "    radio22.configure(state = \"normal\")\n",
    "    v1.set(0)\n",
    "    v2.set(0)\n",
    "\n",
    "v1 = tk.IntVar()\n",
    "v1.set(0)\n",
    "v2 = tk.IntVar()\n",
    "v2.set(0)\n",
    "# Frameの生成と配置\n",
    "frame1 = tk.LabelFrame(root, text = \"Group1\")\n",
    "frame1.pack()\n",
    "# ラジオボタン・オブジェクトの生成と配置\n",
    "radio11 = tk.Radiobutton(frame1, text =\"選択項目#1\", variable=v1, value=1, command=state1)\n",
    "radio11.pack()\n",
    " \n",
    "radio12 = tk.Radiobutton(frame1, text =\"選択項目#2\", variable=v1, value=2, command=state1)\n",
    "radio12.pack()\n",
    " \n",
    "# Frameの生成と配置\n",
    "frame2 = tk.LabelFrame(root ,text= \"Group2\")\n",
    "frame2.pack()\n",
    "# ラジオボタン・オブジェクトの生成と配置\n",
    "radio21 = tk.Radiobutton(frame2, text =\"選択項目#1\", variable=v2, value=1, command=state2)\n",
    "radio21.pack()\n",
    " \n",
    "radio22 = tk.Radiobutton(frame2, text =\"選択項目#2\", variable=v2, value=2, command=state2)\n",
    "radio22.pack()\n",
    " \n",
    "# RESETボタンの生成と配置\n",
    "restbtn = tk.Button(text=\"RESET\", command = reset)\n",
    "restbtn.pack()\n",
    " \n",
    "root.mainloop()\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "root = tk.Tk()\n",
    "root.title(\"RadioBTN\")\n",
    "root.geometry(\"300x250\")\n",
    "\n",
    "def state1():\n",
    "    btn = v1.get()\n",
    "    if btn == 1:\n",
    "        radio12.configure(state=\"disable\")\n",
    "    elif btn == 2:\n",
    "        radio11.configure(state=\"disable\")\n",
    "    elif btn == 0:\n",
    "        pass \n",
    "    else:\n",
    "        print(\"Error\", btn)\n",
    "        \n",
    "def state2():\n",
    "    btn = v2.get()\n",
    "    if btn == 1:\n",
    "        radio22.configure(state=\"disable\")\n",
    "    elif btn == 2:\n",
    "        radio21.configure(state=\"disable\")\n",
    "    elif btn == 0:\n",
    "        pass \n",
    "    else:\n",
    "        print(\"Error\", btn)\n",
    "        \n",
    "def reset():\n",
    "    radio11.configure(state=\"normal\")\n",
    "    radio12.configure(state=\"normal\")\n",
    "    radio21.configure(state=\"normal\")\n",
    "    radio22.configure(state=\"normal\")\n",
    "    v1.set(0)\n",
    "    v2.set(0)\n",
    "\n",
    "v1 = tk.IntVar()\n",
    "v1.set(0)\n",
    "v2 = tk.IntVar()\n",
    "v2.set(0)\n",
    "\n",
    "frame1 = tk.LabelFrame(root, text=\"group1\")\n",
    "frame1.pack()\n",
    "radio11 = tk.Radiobutton(frame1, text=\"select1\", variable=v1, value=1, command=state1)\n",
    "radio11.pack()\n",
    "radio12 = tk.Radiobutton(frame1, text=\"select2\", variable=v1, value=2, command=state1)\n",
    "radio12.pack()\n",
    "\n",
    "frame2 = tk.LabelFrame(root, text=\"group2\")\n",
    "frame2.pack()\n",
    "radio21 = tk.Radiobutton(frame2, text=\"select1\", variable=v2, value=1, command=state2)\n",
    "radio21.pack()\n",
    "radio22 = tk.Radiobutton(frame2, text=\"select2\", variable=v2, value=2, command=state2)\n",
    "radio22.pack()\n",
    "\n",
    "reset_btn = tk.Button(text=\"Reset\", command=reset)\n",
    "reset_btn.pack()\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
